### ISSUE TITLE
Inactieve studenten

### ISSUE THREAD

**Issue by FrontEndCoffee** [hz-competentiemanager/hz-competentiemanager#39]
Moet een uigeschreven student op inactief moeten gaan of verwijderd worden uit het systeem?

**Comment by roelvanendhoven** [comment]
Gezien een student kan herinschrijven lijkt me een inactive state een goed idee

**Comment by FrontEndCoffee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Inactieve studenten](https://trello.com/c/7eUJwKNl/5-inactieve-studenten)
