### ISSUE TITLE
Laravel Models

### ISSUE THREAD

**Issue by markdingemanse** [hz-competentiemanager/hz-competentiemanager#95]
Op het moment wanneer een namespace van een dependency van een model zoals de volgende zou wijzigen zou dit veranderd moeten worden in de code zelf:

```    /**
     * Many to many elequent relation with students. (or collection if called without parentheces).
     *
     * @return Elequent Relation
     */
    public function students()
    {
        return $this->belongsToMany('App\Models\Student', 'project_student', 'project_id', 'student_id');
    } 

```

Wanneer je by je class dependency's App\Models\Student zou toevoegen dan kun je in de code van je model zelf Student::class gebruiken die de volledige namespace van de klasse teruggeeft zodat je model beter bestendig is tegen verandering en je code makkelijker onderhoudbaar is.

**Comment by FrontEndCoffee** [comment]
Dit heeft tevens als voordeel dat je autocompletion in je IDE kunt gebruiken bij het schrijven van deze paden

**Comment by BackEndTea** [comment]
Ik ga vanavond een paar uurtjes pakken om te refactoren, dus neem deze er dan onder andere in mee.

**Comment by BackEndTea** [comment]
Als het goed is wordt dit nu gefixed in #126
